name: Snowflake_CICD_NEW

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
        
      - name: Deploy to DEV
        env:
          # SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          # SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          # SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          # SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          # SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          # SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      
        run: |
          ~/bin/snowsql -q """CREATE SCHEMA IF NOT EXISTS SCHEMACHANGE;
                              CREATE OR REPLACE TABLE SCHEMACHANGE.CHANGE_HISTORY
                             (
                              VERSION VARCHAR
                             ,DESCRIPTION VARCHAR
                             ,SCRIPT VARCHAR
                             ,SCRIPT_TYPE VARCHAR
                             ,CHECKSUM VARCHAR
                             ,EXECUTION_TIME NUMBER
                             ,STATUS VARCHAR
                             ,INSTALLED_BY VARCHAR
                             ,INSTALLED_ON TIMESTAMP_LTZ
                             ,PROJECT VARCHAR
                             );
                          """
          pip install schemachange
          # for sql_file in $(find $GITHUB_WORKSPACE/scripts/versioned -name '*.sql'); do
          #   relative_path="${sql_file#$GITHUB_WORKSPACE/}"
          #   echo $relative_path
          #   snow --config-file $GITHUB_WORKSPACE/config.toml sql -q "EXECUTE IMMEDIATE FROM @snowflake_cicd/branches/main/$relative_path"
          # done
          for dir in "$GITHUB_WORKSPACE/scripts/versioned"/*/; do
              # Extract the subdirectory name
              subdir=$(basename "$dir")
              echo "Found subdirectory: $subdir"
              # Add your logic here (e.g., run SQL files within each subdirectory)
          done


          schemachange -f $GITHUB_WORKSPACE -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_DEV --create-change-history-table
          echo $GITHUB_WORKSPACE

  deploy_qut:
    if: github.ref == 'refs/heads/dev'  # Change this to manually trigger or depend on dev job
    needs: deploy_dev  # Ensures this job runs after dev deployment
    runs-on: ubuntu-latest
    environment: qut
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Deploy to QUT
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          pip install schemachange
          schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_QUT --create-change-history-table
