name: Snowflake_CICD

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
        
      - name: Deploy to DEV
        env:
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }} 
          # SUBDIR: ${{ env.subdir }}
        run: |
          ~/bin/snowsql -f $GITHUB_WORKSPACE/scripts/change_history_table_ddl.sql
          pip install schemachange
          for dir in "$GITHUB_WORKSPACE/scripts"/*/; do
              subdir=$(basename "$dir")
              echo "Found project subdirectory: $subdir"
              FILE_CONTENT2=$(cat "$GITHUB_WORKSPACE/scripts/change_history_project_table_ddl.sql")
              echo "$FILE_CONTENT2"
              FILE_CONTENT=$(cat "$GITHUB_WORKSPACE/scripts/change_history_project_table_ddl.sql" | sed "s/{PROJECT}/$subdir/g")
              echo "$FILE_CONTENT"
              
              ~/bin/snowsql -q "$FILE_CONTENT"
              # schemachange -f $GITHUB_WORKSPACE/scripts/$subdir -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -r $SNOWSQL_ROLE -w $SNOWSQL_WAREHOUSE -d $SNOWSQL_DATABASE -c $SNOWSQL_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_$subdir 
              # ~/bin/snowsql -f $GITHUB_WORKSPACE/scripts/merge_change_history.sql
          done

          

  deploy_qut:
    if: github.ref == 'refs/heads/dev'  # Change this to manually trigger or depend on dev job
    needs: deploy_dev  # Ensures this job runs after dev deployment
    runs-on: ubuntu-latest
    environment: qut
    steps:
      - name: Retrieve repository
        uses: actions/checkout@v3
      
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Deploy to QUT
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          pip install schemachange
          schemachange -f $GITHUB_WORKSPACE -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY_QUT --create-change-history-table
